/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FishingRouteImport } from './routes/fishing'
import { Route as SailingRouteImport } from './routes/sailing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingRoute = FishingRouteImport.update({
  id: '/fishing',
  path: '/fishing',
  getParentRoute: () => rootRouteImport,
} as any)
const SailingRoute = SailingRouteImport.update({
  id: '/sailing',
  path: '/sailing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fishing': typeof FishingRoute
  '/sailing': typeof SailingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fishing': typeof FishingRoute
  '/sailing': typeof SailingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fishing': typeof FishingRoute
  '/sailing': typeof SailingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fishing' | '/sailing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fishing' | '/sailing'
  id: '__root__' | '/' | '/fishing' | '/sailing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FishingRoute: typeof FishingRoute
  SailingRoute: typeof SailingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing': {
      id: '/fishing'
      path: '/fishing'
      fullPath: '/fishing'
      preLoaderRoute: typeof FishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sailing': {
      id: '/sailing'
      path: '/sailing'
      fullPath: '/sailing'
      preLoaderRoute: typeof SailingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FishingRoute: FishingRoute,
  SailingRoute: SailingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
